name: Add project
on:
  workflow_dispatch:
    inputs:
      project-id:
        description: The project id you want to add.
        required: true
        default: "60917032"
jobs:
  add-project:
    name: Add Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      - name: Run add-project.mjs
        run: |
          yarn add-project ${{ github.event.inputs.project-id }}

      - name: Build Website
        run: |
          yarn build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        if: github.ref == 'refs/heads/main'

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Start listening to ${{ github.event.inputs.project-id }}
